"""
Données d'entraînement pour EmbeddingClassifier — 300 exemples
Loi : évolution — plus d'exemples = meilleure classification
Couvre tous les agents de Lucie.
"""

from typing import List, Tuple

TRAINING_EXAMPLES: List[Tuple[str, str]] = [

    # ── computer_control (60 exemples) ──────────────────────────────
    ("ouvre Safari", "computer_control"),
    ("lance Firefox", "computer_control"),
    ("ouvre Chrome", "computer_control"),
    ("ferme Safari", "computer_control"),
    ("ferme la fenêtre", "computer_control"),
    ("ouvre Terminal", "computer_control"),
    ("lance le terminal", "computer_control"),
    ("ouvre VS Code", "computer_control"),
    ("lance Xcode", "computer_control"),
    ("ouvre Finder", "computer_control"),
    ("ouvre les préférences système", "computer_control"),
    ("monte le volume", "computer_control"),
    ("baisse le son", "computer_control"),
    ("coupe le son", "computer_control"),
    ("prends une capture d'écran", "computer_control"),
    ("screenshot", "computer_control"),
    ("copie ce texte", "computer_control"),
    ("colle dans le presse-papier", "computer_control"),
    ("ouvre Spotify", "computer_control"),
    ("lance la musique", "computer_control"),
    ("mets en pause", "computer_control"),
    ("chanson suivante", "computer_control"),
    ("reviens en arrière dans la musique", "computer_control"),
    ("ouvre Discord", "computer_control"),
    ("lance Slack", "computer_control"),
    ("ouvre Notion", "computer_control"),
    ("lance Figma", "computer_control"),
    ("ouvre Telegram", "computer_control"),
    ("ferme toutes les fenêtres", "computer_control"),
    ("minimise la fenêtre", "computer_control"),
    ("agrandis la fenêtre", "computer_control"),
    ("passe en plein écran", "computer_control"),
    ("quitte l'application", "computer_control"),
    ("force quit", "computer_control"),
    ("redémarre le Mac", "computer_control"),
    ("éteins l'ordinateur", "computer_control"),
    ("verrouille l'écran", "computer_control"),
    ("active le mode sombre", "computer_control"),
    ("passe en mode clair", "computer_control"),
    ("augmente la luminosité", "computer_control"),
    ("baisse la luminosité de l'écran", "computer_control"),
    ("connecte le bluetooth", "computer_control"),
    ("active le wifi", "computer_control"),
    ("désactive le wifi", "computer_control"),
    ("ouvre Activity Monitor", "computer_control"),
    ("lance TextEdit", "computer_control"),
    ("ouvre Preview", "computer_control"),
    ("lance Pages", "computer_control"),
    ("ouvre Numbers", "computer_control"),
    ("lance Keynote", "computer_control"),
    ("ouvre le bureau", "computer_control"),
    ("montre le dock", "computer_control"),
    ("cache le dock", "computer_control"),
    ("vide la corbeille", "computer_control"),
    ("ouvre la corbeille", "computer_control"),
    ("cherche un fichier", "computer_control"),
    ("spotlight", "computer_control"),
    ("change de bureau virtuel", "computer_control"),
    ("mission control", "computer_control"),
    ("expose toutes les fenêtres", "computer_control"),

    # ── creator (50 exemples) ────────────────────────────────────────
    ("écris un mail", "creator"),
    ("rédige un email professionnel", "creator"),
    ("écris une lettre de motivation", "creator"),
    ("génère un texte sur l'IA", "creator"),
    ("rédige un article de blog", "creator"),
    ("écris un résumé", "creator"),
    ("fais un résumé de ce texte", "creator"),
    ("traduis ce texte en anglais", "creator"),
    ("traduis en espagnol", "creator"),
    ("corrige les fautes", "creator"),
    ("reformule cette phrase", "creator"),
    ("améliore ce texte", "creator"),
    ("écris une description produit", "creator"),
    ("génère un slogan", "creator"),
    ("crée un post LinkedIn", "creator"),
    ("rédige un tweet", "creator"),
    ("écris une bio", "creator"),
    ("génère des idées de contenu", "creator"),
    ("écris un poème", "creator"),
    ("rédige une histoire courte", "creator"),
    ("crée un script vidéo", "creator"),
    ("rédige une présentation", "creator"),
    ("écris un rapport", "creator"),
    ("génère un plan de projet", "creator"),
    ("rédige un compte-rendu", "creator"),
    ("écris une proposition commerciale", "creator"),
    ("génère du code Python", "creator"),
    ("écris une fonction JavaScript", "creator"),
    ("crée un README", "creator"),
    ("rédige la documentation", "creator"),
    ("explique ce concept", "creator"),
    ("explique-moi le machine learning", "creator"),
    ("qu'est-ce que le RAG", "creator"),
    ("comment fonctionne FAISS", "creator"),
    ("écris un email de relance", "creator"),
    ("rédige un message de remerciement", "creator"),
    ("génère des questions d'entretien", "creator"),
    ("crée un quiz", "creator"),
    ("écris une FAQ", "creator"),
    ("rédige les conditions générales", "creator"),
    ("génère un contrat simple", "creator"),
    ("écris une recette de cuisine", "creator"),
    ("crée un programme d'entraînement", "creator"),
    ("rédige un plan de régime", "creator"),
    ("génère des noms de domaine", "creator"),
    ("propose des noms pour mon projet", "creator"),
    ("écris une accroche publicitaire", "creator"),
    ("rédige un brief créatif", "creator"),
    ("génère des hashtags", "creator"),
    ("crée un plan de communication", "creator"),

    # ── reminder (40 exemples) ───────────────────────────────────────
    ("rappelle-moi demain", "reminder"),
    ("crée un rappel", "reminder"),
    ("mets un rappel à 9h", "reminder"),
    ("rappelle-moi dans une heure", "reminder"),
    ("rappelle-moi ce soir", "reminder"),
    ("rappelle-moi lundi matin", "reminder"),
    ("ajoute un rappel pour la réunion", "reminder"),
    ("rappelle-moi d'appeler Paul", "reminder"),
    ("mets une alarme demain", "reminder"),
    ("réveille-moi à 7h", "reminder"),
    ("rappelle-moi de prendre mes médicaments", "reminder"),
    ("crée un rappel quotidien", "reminder"),
    ("rappelle-moi chaque lundi", "reminder"),
    ("ajoute un rappel récurrent", "reminder"),
    ("rappelle-moi dans 30 minutes", "reminder"),
    ("alerte dans 2 heures", "reminder"),
    ("notification demain à midi", "reminder"),
    ("rappelle-moi de sortir les poubelles", "reminder"),
    ("rappelle-moi d'envoyer le rapport", "reminder"),
    ("mets un rappel pour mon rendez-vous", "reminder"),
    ("rappelle-moi de faire les courses", "reminder"),
    ("alerte pour la deadline vendredi", "reminder"),
    ("rappelle-moi de rappeler Marie", "reminder"),
    ("crée une alerte pour dans 1 semaine", "reminder"),
    ("rappelle-moi de payer la facture", "reminder"),
    ("mets un rappel pour le dentiste", "reminder"),
    ("rappelle-moi de renouveler mon abonnement", "reminder"),
    ("alerte pour la réunion de demain", "reminder"),
    ("rappelle-moi d'arroser les plantes", "reminder"),
    ("mets une alarme dans 10 minutes", "reminder"),
    ("rappelle-moi ce weekend", "reminder"),
    ("crée un rappel pour ce soir 20h", "reminder"),
    ("rappelle-moi de vérifier les emails", "reminder"),
    ("alerte quand la batterie est faible", "reminder"),
    ("rappelle-moi de sauvegarder", "reminder"),
    ("mets un rappel pour la livraison", "reminder"),
    ("rappelle-moi d'appeler le médecin", "reminder"),
    ("crée un rappel pour mon anniversaire", "reminder"),
    ("rappelle-moi de souhaiter bonne fête", "reminder"),
    ("alerte dans 5 minutes", "reminder"),

    # ── file_agent (40 exemples) ─────────────────────────────────────
    ("crée un fichier texte", "file_agent"),
    ("crée un nouveau fichier", "file_agent"),
    ("lis ce fichier", "file_agent"),
    ("ouvre ce document", "file_agent"),
    ("modifie le fichier config", "file_agent"),
    ("supprime ce fichier", "file_agent"),
    ("déplace ce fichier", "file_agent"),
    ("copie ce fichier", "file_agent"),
    ("renomme ce fichier", "file_agent"),
    ("crée un dossier", "file_agent"),
    ("liste les fichiers", "file_agent"),
    ("montre le contenu du dossier", "file_agent"),
    ("cherche dans les fichiers", "file_agent"),
    ("trouve tous les PDF", "file_agent"),
    ("compresse ce dossier", "file_agent"),
    ("décompresse l'archive", "file_agent"),
    ("sauvegarde ce fichier", "file_agent"),
    ("exporte en PDF", "file_agent"),
    ("convertis ce fichier", "file_agent"),
    ("écris dans le fichier", "file_agent"),
    ("ajoute une ligne au fichier", "file_agent"),
    ("crée un fichier JSON", "file_agent"),
    ("crée un CSV", "file_agent"),
    ("lis le fichier config.yaml", "file_agent"),
    ("modifie le README", "file_agent"),
    ("crée un script Python", "file_agent"),
    ("sauvegarde sur le bureau", "file_agent"),
    ("déplace vers Documents", "file_agent"),
    ("vide le dossier temporaire", "file_agent"),
    ("trouve les fichiers récents", "file_agent"),
    ("cherche les gros fichiers", "file_agent"),
    ("duplique ce document", "file_agent"),
    ("crée un lien symbolique", "file_agent"),
    ("change les permissions", "file_agent"),
    ("montre la taille du dossier", "file_agent"),
    ("combien pèse ce fichier", "file_agent"),
    ("crée un fichier vide", "file_agent"),
    ("écrase le fichier existant", "file_agent"),
    ("fusionne ces deux fichiers", "file_agent"),
    ("divise ce fichier", "file_agent"),

    # ── knowledge_agent (30 exemples) ───────────────────────────────
    ("analyse ce document", "knowledge_agent"),
    ("résume ce PDF", "knowledge_agent"),
    ("que dit ce fichier", "knowledge_agent"),
    ("extrais les informations clés", "knowledge_agent"),
    ("analyse ce contrat", "knowledge_agent"),
    ("lis et résume", "knowledge_agent"),
    ("que contient ce document", "knowledge_agent"),
    ("analyse ce rapport", "knowledge_agent"),
    ("extrais les chiffres importants", "knowledge_agent"),
    ("compare ces deux documents", "knowledge_agent"),
    ("trouve les contradictions", "knowledge_agent"),
    ("cherche dans ma base de connaissances", "knowledge_agent"),
    ("qu'est-ce que j'ai noté sur ce sujet", "knowledge_agent"),
    ("retrouve l'information sur Python", "knowledge_agent"),
    ("cherche dans mes notes", "knowledge_agent"),
    ("analyse cette image", "knowledge_agent"),
    ("que vois-tu sur cette photo", "knowledge_agent"),
    ("lis ce texte scanné", "knowledge_agent"),
    ("extrais le texte de cette image", "knowledge_agent"),
    ("analyse ce tableau", "knowledge_agent"),
    ("interprète ces données", "knowledge_agent"),
    ("que signifient ces chiffres", "knowledge_agent"),
    ("analyse ce graphique", "knowledge_agent"),
    ("vérifie les faits dans ce document", "knowledge_agent"),
    ("trouve les sources", "knowledge_agent"),
    ("recherche dans l'historique", "knowledge_agent"),
    ("qu'ai-je dit hier à propos de", "knowledge_agent"),
    ("retrouve notre conversation sur", "knowledge_agent"),
    ("analyse ce code", "knowledge_agent"),
    ("explique ce que fait ce script", "knowledge_agent"),

    # ── workspace_agent (30 exemples) ───────────────────────────────
    ("organise mes fenêtres", "workspace_agent"),
    ("mets Safari et VS Code côte à côte", "workspace_agent"),
    ("split screen", "workspace_agent"),
    ("fenêtres côte à côte", "workspace_agent"),
    ("arrange les fenêtres", "workspace_agent"),
    ("layout développeur", "workspace_agent"),
    ("mode présentation", "workspace_agent"),
    ("organisation bureau", "workspace_agent"),
    ("mets le terminal en bas", "workspace_agent"),
    ("Safari à gauche Notion à droite", "workspace_agent"),
    ("plein écran pour Safari", "workspace_agent"),
    ("fenêtre centrée", "workspace_agent"),
    ("organisation des espaces de travail", "workspace_agent"),
    ("bureau propre", "workspace_agent"),
    ("range les fenêtres ouvertes", "workspace_agent"),
    ("layout meeting", "workspace_agent"),
    ("mode focus", "workspace_agent"),
    ("espace de travail musique", "workspace_agent"),
    ("organise pour coder", "workspace_agent"),
    ("mets Figma en plein écran", "workspace_agent"),
    ("deux fenêtres en haut une en bas", "workspace_agent"),
    ("trois colonnes", "workspace_agent"),
    ("quatre fenêtres égales", "workspace_agent"),
    ("fenêtre principale à gauche", "workspace_agent"),
    ("terminal en bas à droite", "workspace_agent"),
    ("navigateur en haut", "workspace_agent"),
    ("éditeur à gauche terminal à droite", "workspace_agent"),
    ("restore le layout précédent", "workspace_agent"),
    ("sauvegarde ce layout", "workspace_agent"),
    ("applique le layout bureau", "workspace_agent"),
]


def get_training_examples() -> List[Tuple[str, str]]:
    """Retourne les 300 exemples d'entraînement."""
    return TRAINING_EXAMPLES


def get_examples_by_label(label: str) -> List[str]:
    """Retourne tous les exemples d'une catégorie."""
    return [text for text, lbl in TRAINING_EXAMPLES if lbl == label]


def get_labels() -> List[str]:
    """Retourne la liste des labels uniques."""
    return list(set(lbl for _, lbl in TRAINING_EXAMPLES))

# ── exemples supplémentaires pour atteindre 300 ─────────────────────
TRAINING_EXAMPLES += [

    # computer_control (10 de plus)
    ("ouvre les réglages", "computer_control"),
    ("lance l'app Musique", "computer_control"),
    ("ouvre FaceTime", "computer_control"),
    ("lance Photo Booth", "computer_control"),
    ("ouvre Maps", "computer_control"),
    ("lance l'app Podcast", "computer_control"),
    ("ouvre Contacts", "computer_control"),
    ("lance l'app TV", "computer_control"),
    ("ouvre Calendrier", "computer_control"),
    ("lance l'app Horloge", "computer_control"),

    # creator (10 de plus)
    ("rédige une newsletter", "creator"),
    ("génère un plan marketing", "creator"),
    ("écris un guide pratique", "creator"),
    ("crée un template d'email", "creator"),
    ("génère des idées de startup", "creator"),
    ("rédige une fiche produit", "creator"),
    ("écris un communiqué de presse", "creator"),
    ("génère un pitch deck", "creator"),
    ("rédige une offre d'emploi", "creator"),
    ("crée un syllabus de formation", "creator"),

    # reminder (10 de plus)
    ("rappelle-moi de faire du sport", "reminder"),
    ("alerte tous les matins à 8h", "reminder"),
    ("rappelle-moi de méditer", "reminder"),
    ("crée un rappel pour la gym", "reminder"),
    ("rappelle-moi de boire de l'eau", "reminder"),
    ("alerte pour le match ce soir", "reminder"),
    ("rappelle-moi de lire", "reminder"),
    ("mets un rappel hebdomadaire", "reminder"),
    ("rappelle-moi de vérifier les stocks", "reminder"),
    ("alerte avant la deadline", "reminder"),

    # file_agent (10 de plus)
    ("crée un fichier markdown", "file_agent"),
    ("génère un fichier HTML", "file_agent"),
    ("crée un fichier de log", "file_agent"),
    ("archive ces documents", "file_agent"),
    ("nettoie les fichiers temporaires", "file_agent"),
    ("organise les photos", "file_agent"),
    ("trie les fichiers par date", "file_agent"),
    ("crée un backup", "file_agent"),
    ("synchronise les fichiers", "file_agent"),
    ("vérifie l'intégrité du fichier", "file_agent"),

    # knowledge_agent (5 de plus)
    ("analyse ces statistiques", "knowledge_agent"),
    ("résume cette page web", "knowledge_agent"),
    ("extrais les dates importantes", "knowledge_agent"),
    ("trouve les personnes mentionnées", "knowledge_agent"),
    ("analyse le sentiment de ce texte", "knowledge_agent"),

    # workspace_agent (5 de plus)
    ("layout pour la réunion", "workspace_agent"),
    ("organise pour le design", "workspace_agent"),
    ("espace de travail écriture", "workspace_agent"),
    ("deux moniteurs côte à côte", "workspace_agent"),
    ("fenêtres en cascade", "workspace_agent"),
]
