"""
Profils sandbox macOS pour l'isolation des agents.

macOS sandbox-exec utilise des profils en Scheme (TinyScheme)
qui définissent les règles d'accès pour chaque processus.

3 catégories de profils :
- RESTRICTED : agents sans accès réseau ni fichiers (par défaut)
- FILE_ACCESS : agents avec accès à un répertoire spécifique
- NETWORK_ACCESS : agents avec accès réseau limité

IMPORTANT : sandbox-exec est un outil macOS natif, pas un container.
Il utilise le Mandatory Access Control (MAC) du noyau XNU via
le framework Seatbelt. C'est le même mécanisme utilisé par les
applications sandboxées du Mac App Store.

LIMITATION : sandbox-exec est deprecated depuis macOS 10.15
mais reste fonctionnel. L'alternative est App Sandbox via
entitlements, mais elle nécessite une app signée. Pour un
processus Python lancé via subprocess, sandbox-exec reste
la meilleure option.
"""

from __future__ import annotations

import os
import tempfile
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..utils.logger import logger


class SandboxTier(Enum):
    """Niveaux de sandbox par catégorie d'agent."""
    RESTRICTED = "restricted"     # Pas de réseau, pas de fichiers
    FILE_ACCESS = "file_access"   # Accès à un répertoire dédié
    NETWORK_ACCESS = "network"    # Accès réseau limité + fichiers
    SENSITIVE = "sensitive"       # Accès fichiers + crypto, pas de réseau


# Mapping agent → tier de sandbox
AGENT_SANDBOX_MAP: Dict[str, SandboxTier] = {
    "FileAgent": SandboxTier.FILE_ACCESS,
    "DocumentAgent": SandboxTier.FILE_ACCESS,
    "ComputerControlAgent": SandboxTier.RESTRICTED,
    "WorkspaceAgent": SandboxTier.RESTRICTED,
    "AppleEcosystemAgent": SandboxTier.RESTRICTED,
    "CalendarAgent": SandboxTier.RESTRICTED,
    "ReminderAgent": SandboxTier.RESTRICTED,
    "SmartMailAgent": SandboxTier.NETWORK_ACCESS,
    "KnowledgeAgent": SandboxTier.NETWORK_ACCESS,
    "AccountingAgent": SandboxTier.SENSITIVE,
    "CreatorAgent": SandboxTier.FILE_ACCESS,
    "CodeDebugAgent": SandboxTier.FILE_ACCESS,
    "PlannerAgent": SandboxTier.RESTRICTED,
}


def generate_sandbox_profile(
    tier: SandboxTier,
    agent_name: str,
    work_dir: str,
    socket_path: str,
    extra_paths: Optional[List[str]] = None,
) -> str:
    """
    Génère un profil sandbox macOS (.sb) en Scheme.

    Le profil est basé sur le principe du moindre privilège :
    - DENY ALL par défaut
    - ALLOW uniquement ce qui est nécessaire

    Args:
        tier: Niveau de restriction
        agent_name: Nom de l'agent (pour les commentaires)
        work_dir: Répertoire de travail dédié à l'agent
        socket_path: Chemin du socket Unix pour l'IPC
        extra_paths: Chemins supplémentaires autorisés en lecture

    Returns:
        Contenu du fichier .sb
    """
    extra_paths = extra_paths or []

    # Base commune — deny all par défaut
    profile = f""";; Sandbox profile for agent: {agent_name}
;; Tier: {tier.value}
;; Generated by Lucie SandboxManager
;; WARNING: Do not edit manually

(version 1)

;; ── DENY ALL par défaut ──────────────────────────
(deny default)

;; ── Permissions de base (tous les agents) ────────

;; Autoriser le processus à s'exécuter
(allow process-exec*)

;; Autoriser la lecture des bibliothèques système
(allow file-read*
    (subpath "/usr/lib")
    (subpath "/usr/local/lib")
    (subpath "/System/Library")
    (subpath "/Library/Frameworks")
    (subpath "/opt/homebrew/lib")
)

;; Autoriser la lecture de Python et ses packages
(allow file-read*
    (subpath "/usr/local/Cellar/python")
    (subpath "/opt/homebrew/Cellar/python")
    (subpath "/opt/homebrew/lib/python3")
    (regex #"/.*site-packages/.*")
    (regex #"/.*\\.pyc$")
)

;; Autoriser les fichiers temporaires dans le répertoire dédié
(allow file-read* file-write*
    (subpath "{work_dir}")
)

;; Autoriser le socket Unix pour l'IPC avec l'EventBus
(allow network-outbound
    (literal "{socket_path}")
)
(allow file-read* file-write*
    (literal "{socket_path}")
)

;; Autoriser /dev/urandom (crypto)
(allow file-read*
    (literal "/dev/urandom")
    (literal "/dev/random")
)

;; Autoriser sysctl pour les infos système basiques
(allow sysctl-read)

;; ── INTERDICTIONS EXPLICITES ─────────────────────

;; Bloquer les appels système dangereux
(deny process-fork)           ;; Pas de fork (empêche l'évasion)
(deny signal)                 ;; Pas de signaux inter-processus
(deny system-socket)          ;; Pas de raw sockets

;; Bloquer ptrace et debugging
(deny process-info-pidinfo)
(deny process-info-setcontrol)

;; Bloquer l'accès au Keychain (sauf SENSITIVE)
(deny mach-lookup
    (global-name "com.apple.SecurityServer")
)

;; Bloquer l'accès aux préférences système
(deny file-read* file-write*
    (subpath "/Library/Preferences")
    (regex #"/Users/.*/Library/Preferences/.*")
)
"""

    # Permissions spécifiques par tier
    if tier == SandboxTier.FILE_ACCESS:
        profile += f"""
;; ── FILE_ACCESS : accès fichiers étendu ──────────
;; Lecture dans les dossiers utilisateur courants
(allow file-read*
    (subpath "/Users")
)
;; Écriture uniquement dans le répertoire de travail
;; (déjà autorisé ci-dessus via work_dir)
"""
        for path in extra_paths:
            profile += f'(allow file-read* (subpath "{path}"))\n'

    elif tier == SandboxTier.NETWORK_ACCESS:
        profile += f"""
;; ── NETWORK_ACCESS : réseau limité ───────────────
;; Autoriser les connexions sortantes TCP (HTTP/HTTPS)
(allow network-outbound
    (remote tcp "*:80")
    (remote tcp "*:443")
)

;; Autoriser la résolution DNS
(allow network-outbound
    (remote udp "*:53")
)
(allow file-read*
    (literal "/etc/resolv.conf")
    (literal "/etc/hosts")
)

;; Lecture fichiers pour le contexte
(allow file-read*
    (subpath "/Users")
)
"""

    elif tier == SandboxTier.SENSITIVE:
        profile += f"""
;; ── SENSITIVE : crypto + fichiers, pas de réseau ─
;; Accès au Keychain (override du deny global)
(allow mach-lookup
    (global-name "com.apple.SecurityServer")
    (global-name "com.apple.securityd")
)

;; Lecture fichiers étendue
(allow file-read*
    (subpath "/Users")
)

;; AUCUN accès réseau (deny default s'applique)
"""

    elif tier == SandboxTier.RESTRICTED:
        profile += """
;; ── RESTRICTED : minimum absolu ──────────────────
;; Pas de fichiers hors work_dir
;; Pas de réseau
;; Pas de Keychain
"""

    profile += """
;; ── Fin du profil ────────────────────────────────
"""

    return profile


def write_sandbox_profile(
    tier: SandboxTier,
    agent_name: str,
    work_dir: str,
    socket_path: str,
    output_dir: Optional[str] = None,
) -> Path:
    """
    Écrit le profil sandbox dans un fichier .sb.

    Returns:
        Chemin du fichier .sb créé
    """
    if output_dir is None:
        output_dir = tempfile.mkdtemp(prefix="lucie-sandbox-")

    profile_content = generate_sandbox_profile(
        tier, agent_name, work_dir, socket_path,
    )

    profile_path = Path(output_dir) / f"{agent_name.lower()}.sb"
    profile_path.write_text(profile_content, encoding="utf-8")

    logger.debug(f"Profil sandbox écrit: {profile_path}")
    return profile_path
